### ISSUE TITLE
im getting new error after the recipe fix i report earlier.

### ISSUE THREAD

**Issue by vexify1337** [esx-framework/esx-recipes#19]
im getting new error after the recipe fix i report earlier. 
![image](https://github.com/esx-framework/esx-recipes/assets/122513007/9af925a3-67e4-4c0d-b223-94fc0f49c4a4)

**Comment by vexify1337** [comment]
perhaps you could delete the loading screen thing of the recipe if it is not needed?

**Comment by Cyzxin** [comment]
#20 this is resolved in this pr

**Comment by jbdevic** [comment]
Thanks, that's been fixed
